"""Write web/src/marketing/pages/schema.generated.ts from the live SQLAlchemy schema so the
/privacy page can only ever show what the database actually has.

    cd trail && ../.venv/bin/python -m trail.server.gen_schema

tests/test_privacy.py fails when the generated file is stale."""
from __future__ import annotations

import json
import sys
from pathlib import Path

from trail.server.models import schema_description

OUT = Path(__file__).resolve().parents[2] / "web" / "src" / "marketing" / "pages" / "schema.generated.ts"


def render() -> str:
    tables = schema_description()
    body = json.dumps(tables, indent=2, ensure_ascii=False)
    return (
        "// Generated by `python -m trail.server.gen_schema` from trail/server/models.py. Do not edit;\n"
        "// tests/test_privacy.py fails when this file does not match the database schema.\n"
        "export type StoredColumn = { name: string; type: string; what: string };\n"
        "export type StoredTable = { table: string; why: string; columns: StoredColumn[] };\n"
        f"export const STORED_TABLES: StoredTable[] = {body};\n"
    )


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = render()
    if "--check" in argv:
        return 0 if OUT.exists() and OUT.read_text() == text else 1
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
