#!/usr/bin/env node
// Writes manifest.json and src/config.js from manifest.template.json for one app origin.
//
//   node build.js                                  # APP_ORIGIN env or https://longhand.app
//   node build.js --origin http://localhost:5173   # local dev against `vite dev`
//   node build.js --origin https://longhand.app --dev   # production origin plus localhost for testing
//
// The origin appears in externally_connectable (the web app talks to the extension over
// chrome.runtime.sendMessage) and in config.js (popup links, origin check). It is not a host
// permission: externally_connectable needs none.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const origin = (flag("--origin") || process.env.APP_ORIGIN || "https://longhand.app").replace(/\/$/, "");
const dev = args.includes("--dev");
if (!/^https?:\/\/[^/]+$/.test(origin)) {
  console.error(`APP_ORIGIN must be scheme + host only, e.g. https://longhand.app (got ${origin})`);
  process.exit(1);
}
const extra = dev ? ["http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:8100"] : [];
const origins = [origin, ...extra.filter((o) => o !== origin)];

const template = JSON.parse(readFileSync(join(here, "manifest.template.json"), "utf8"));
const manifest = JSON.parse(JSON.stringify(template).replaceAll("__APP_ORIGIN__", origin));
manifest.externally_connectable.matches = origins.map((o) => `${o}/*`);
writeFileSync(join(here, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
writeFileSync(
  join(here, "src", "config.js"),
  `// Generated by build.js; do not edit. Rebuild with: node build.js --origin ${origin}${dev ? " --dev" : ""}\n` +
    `export const APP_ORIGIN = ${JSON.stringify(origin)};\n` +
    `export const ALLOWED_ORIGINS = ${JSON.stringify(origins)};\n`,
);
console.log(`manifest.json written for ${origins.join(", ")}`);
