// Generated by `python -m trail.server.gen_schema` from trail/server/models.py. Do not edit;
// tests/test_privacy.py fails when this file does not match the database schema.
export type StoredColumn = { name: string; type: string; what: string };
export type StoredTable = { table: string; why: string; columns: StoredColumn[] };
export const STORED_TABLES: StoredTable[] = [
  {
    "table": "transparency_log",
    "why": "Append-only public log of every checkpoint we sign, so we cannot quietly re-sign history. Never deleted, even when an account is.",
    "columns": [
      {
        "name": "seq",
        "type": "INTEGER",
        "what": "position in the log"
      },
      {
        "name": "entry_hash",
        "type": "VARCHAR(64)",
        "what": "fingerprint of this entry, chained to the previous one"
      },
      {
        "name": "prev",
        "type": "VARCHAR(64)",
        "what": "the previous entry's fingerprint"
      },
      {
        "name": "checkpoint_hash",
        "type": "VARCHAR(64)",
        "what": "fingerprint of the checkpoint"
      },
      {
        "name": "ts",
        "type": "VARCHAR(32)",
        "what": "when it was signed"
      }
    ]
  },
  {
    "table": "users",
    "why": "One row per account.",
    "columns": [
      {
        "name": "id",
        "type": "VARCHAR(32)",
        "what": "random id"
      },
      {
        "name": "email",
        "type": "VARCHAR(254)",
        "what": "where login links and renewal reminders go"
      },
      {
        "name": "created_at",
        "type": "DATETIME",
        "what": "when the account was made"
      },
      {
        "name": "last_login_at",
        "type": "DATETIME",
        "what": "when you last used a login link"
      },
      {
        "name": "trial_started_at",
        "type": "DATETIME",
        "what": "when your first replay played; the 14 days count from here"
      },
      {
        "name": "free_until",
        "type": "DATETIME",
        "what": "end of any free semester earned with invites"
      },
      {
        "name": "referral_code",
        "type": "VARCHAR(16)",
        "what": "the code in your invite link"
      },
      {
        "name": "referred_by",
        "type": "VARCHAR(32)",
        "what": "who invited you, if anyone"
      },
      {
        "name": "referral_credits",
        "type": "INTEGER",
        "what": "how many free semesters invites have earned you (max 3)"
      },
      {
        "name": "stripe_customer_id",
        "type": "VARCHAR(64)",
        "what": "so Stripe can find your subscription; we never see your card"
      },
      {
        "name": "renewal_reminded_for",
        "type": "DATETIME",
        "what": "which renewal we last emailed you about, so we do not email twice"
      }
    ]
  },
  {
    "table": "waitlist",
    "why": "People who asked to hear when the Chrome Web Store listing is live.",
    "columns": [
      {
        "name": "email",
        "type": "VARCHAR(254)",
        "what": "the address they typed"
      },
      {
        "name": "created_at",
        "type": "DATETIME",
        "what": "when they asked"
      },
      {
        "name": "source",
        "type": "VARCHAR(40)",
        "what": "which page had the form"
      }
    ]
  },
  {
    "table": "api_tokens",
    "why": "Lets the extension ask us to sign checkpoints.",
    "columns": [
      {
        "name": "id",
        "type": "VARCHAR(32)",
        "what": "random id"
      },
      {
        "name": "user_id",
        "type": "VARCHAR(32)",
        "what": "whose extension"
      },
      {
        "name": "token_hash",
        "type": "VARCHAR(64)",
        "what": "a hash of the token, never the token itself"
      },
      {
        "name": "label",
        "type": "VARCHAR(32)",
        "what": "which client holds it (always \"extension\" today)"
      },
      {
        "name": "created_at",
        "type": "DATETIME",
        "what": "when it was issued"
      },
      {
        "name": "last_used_at",
        "type": "DATETIME",
        "what": "last checkpoint request"
      },
      {
        "name": "revoked_at",
        "type": "DATETIME",
        "what": "when it was replaced or revoked, if it was"
      }
    ]
  },
  {
    "table": "checkpoints",
    "why": "One row per signed checkpoint: the fingerprint of your record at a moment, roughly every ten minutes of writing.",
    "columns": [
      {
        "name": "user_id",
        "type": "VARCHAR(32)",
        "what": "whose record"
      },
      {
        "name": "doc",
        "type": "VARCHAR(200)",
        "what": "a random id the extension made up for the document; not the editor's id, not the title"
      },
      {
        "name": "seq",
        "type": "INTEGER",
        "what": "which checkpoint this is for that document (0, 1, 2, ...)"
      },
      {
        "name": "hash",
        "type": "VARCHAR(64)",
        "what": "the 64-character fingerprint of the checkpoint"
      },
      {
        "name": "body",
        "type": "TEXT",
        "what": "what was signed: per-session chain-head hashes, event counts and timestamps, as JSON. No text."
      },
      {
        "name": "signature",
        "type": "VARCHAR(128)",
        "what": "our signature over the body"
      },
      {
        "name": "key_id",
        "type": "VARCHAR(16)",
        "what": "which signing key we used"
      }
    ]
  },
  {
    "table": "docs",
    "why": "One row per document the extension has had signed, so the app can show when it was last signed.",
    "columns": [
      {
        "name": "user_id",
        "type": "VARCHAR(32)",
        "what": "whose document"
      },
      {
        "name": "doc",
        "type": "VARCHAR(200)",
        "what": "the same random id as in checkpoints; not the editor's id, not the title"
      },
      {
        "name": "first_seen",
        "type": "VARCHAR(32)",
        "what": "first checkpoint time"
      },
      {
        "name": "last_seen",
        "type": "VARCHAR(32)",
        "what": "latest checkpoint time"
      },
      {
        "name": "last_checkpoint",
        "type": "VARCHAR(32)",
        "what": "time of the latest signature"
      }
    ]
  },
  {
    "table": "magic_links",
    "why": "Login links. Each works once and expires 30 minutes after it is sent.",
    "columns": [
      {
        "name": "id",
        "type": "VARCHAR(32)",
        "what": "random id"
      },
      {
        "name": "user_id",
        "type": "VARCHAR(32)",
        "what": "who it signs in"
      },
      {
        "name": "token_hash",
        "type": "VARCHAR(64)",
        "what": "a hash of the link token; the token itself is only in your email"
      },
      {
        "name": "created_at",
        "type": "DATETIME",
        "what": "when it was sent"
      },
      {
        "name": "expires_at",
        "type": "DATETIME",
        "what": "when it stops working"
      },
      {
        "name": "used_at",
        "type": "DATETIME",
        "what": "when it was used, if it was"
      }
    ]
  },
  {
    "table": "referrals",
    "why": "Counting invites toward a free semester.",
    "columns": [
      {
        "name": "id",
        "type": "VARCHAR(32)",
        "what": "random id"
      },
      {
        "name": "referrer_id",
        "type": "VARCHAR(32)",
        "what": "who invited"
      },
      {
        "name": "referred_id",
        "type": "VARCHAR(32)",
        "what": "who accepted"
      },
      {
        "name": "created_at",
        "type": "DATETIME",
        "what": "when the friend signed up with the code"
      },
      {
        "name": "activated_at",
        "type": "DATETIME",
        "what": "when the friend played a first replay"
      },
      {
        "name": "credited",
        "type": "BOOLEAN",
        "what": "whether this invite has already counted toward a free semester"
      }
    ]
  },
  {
    "table": "sessions",
    "why": "Keeps you signed in to the web app.",
    "columns": [
      {
        "name": "id",
        "type": "VARCHAR(32)",
        "what": "random id"
      },
      {
        "name": "user_id",
        "type": "VARCHAR(32)",
        "what": "whose login"
      },
      {
        "name": "token_hash",
        "type": "VARCHAR(64)",
        "what": "a hash of the cookie value, never the cookie itself"
      },
      {
        "name": "created_at",
        "type": "DATETIME",
        "what": "when you signed in"
      },
      {
        "name": "expires_at",
        "type": "DATETIME",
        "what": "when it stops working (90 days)"
      },
      {
        "name": "last_seen_at",
        "type": "DATETIME",
        "what": "last request with it"
      }
    ]
  },
  {
    "table": "subscriptions",
    "why": "A copy of what Stripe tells us about your plan.",
    "columns": [
      {
        "name": "id",
        "type": "VARCHAR(64)",
        "what": "the Stripe subscription id"
      },
      {
        "name": "user_id",
        "type": "VARCHAR(32)",
        "what": "whose plan"
      },
      {
        "name": "plan",
        "type": "VARCHAR(16)",
        "what": "semester or monthly"
      },
      {
        "name": "status",
        "type": "VARCHAR(32)",
        "what": "active, past_due, canceled, and so on, as Stripe reports it"
      },
      {
        "name": "current_period_end",
        "type": "DATETIME",
        "what": "when it renews or ends"
      },
      {
        "name": "cancel_at_period_end",
        "type": "BOOLEAN",
        "what": "whether you asked it to stop at the end of the period"
      },
      {
        "name": "created_at",
        "type": "DATETIME",
        "what": "when it started"
      },
      {
        "name": "updated_at",
        "type": "DATETIME",
        "what": "last change from Stripe"
      }
    ]
  }
];
