// Generated by build.js; do not edit. Rebuild with: node build.js --origin https://trail-production-36dc.up.railway.app --dev
export const APP_ORIGIN = "https://trail-production-36dc.up.railway.app";
export const ALLOWED_ORIGINS = ["https://trail-production-36dc.up.railway.app","http://localhost:5173","http://127.0.0.1:5173","http://localhost:8100","http://127.0.0.1:8100"];
