// Generated by build.js; do not edit. Rebuild with: node build.js --origin https://longhand.app
export const APP_ORIGIN = "https://longhand.app";
export const ALLOWED_ORIGINS = ["https://longhand.app"];
