// Generated by build.js; do not edit. Rebuild with: node build.js --origin http://127.0.0.1:8100
export const APP_ORIGIN = "http://127.0.0.1:8100";
export const ALLOWED_ORIGINS = ["http://127.0.0.1:8100"];
