// Mock fixtures for VITE_MOCK=1. The events are REAL recorder events generated by the Python
// simulator (trail.synthetic.Writer) via fixtures/make_fixtures.py, so replay, analysis and
// the designer's time-lapse behave exactly as they will with a live extension.
import type { Checkpoint, Essay, Me, TrailEvent } from './types';
import { analyse } from './analysis';
import mixed from './fixtures/mock-mixed.json';
import heavy from './fixtures/mock-heavy_paster.json';
import honest from './fixtures/mock-honest.json';

type Fixture = { profile: string; events: TrailEvent[] };

const FIXTURES: { title: string; editor: string; fixture: Fixture }[] = [
  { title: 'Is free will compatible with determinism?', editor: 'docs', fixture: mixed as unknown as Fixture },
  { title: 'The ethics of predictive policing', editor: 'notion', fixture: heavy as unknown as Fixture },
  { title: 'Reading response: Arendt on action', editor: 'word', fixture: honest as unknown as Fixture },
];

export const mockEvents = new Map<string, TrailEvent[]>();
export const mockEssays: Essay[] = FIXTURES.map(({ title, editor, fixture }) => {
  const events = fixture.events;
  const id = events[0].doc;
  mockEvents.set(id, events);
  const a = analyse(events);
  return {
    id,
    title,
    editor,
    firstSeen: a.first_event || events[0].ts,
    lastSeen: a.last_event || events[events.length - 1].ts,
    typed: a.cadence.typed_chars,
    pasted: a.pastes.pasted_chars,
    deleted: a.cadence.deleted_chars,
    events: events.length,
    sessions: a.sessions.length,
    words: a.document.final_words,
  };
});

export const mockMe: Me = {
  id: 'mock-user',
  email: 'sam@student.example',
  plan: 'trial',
  entitled: true,
  trialStartedAt: '2026-09-19T21:10:00.000000Z',
  trialEndsAt: '2026-10-03T21:10:00.000000Z',
  currentPeriodEnd: null,
  cancelAtPeriodEnd: false,
  referralCode: 'SAM4K2QX',
  referrals: 1,
  referralCredits: 0,
  freeUntil: null,
  createdAt: '2026-09-19T21:04:11.000000Z',
  billing: { configured: true, freeAccess: false, hasCustomer: false, refundable: false },
};

export function mockCheckpoints(id: string): Checkpoint[] {
  const events = mockEvents.get(id);
  if (!events) return [];
  // A plausible, unsigned-looking checkpoint shape for layout work; signatures are not real.
  const heads: Record<string, { seq: number; hash: string; first_ts: string }> = {};
  for (const e of events) {
    const h = heads[e.session];
    if (!h) heads[e.session] = { seq: e.seq, hash: e.hash, first_ts: e.ts };
    else if (e.seq > h.seq) {
      h.seq = e.seq;
      h.hash = e.hash;
    }
  }
  const last = events[events.length - 1];
  return [
    {
      body: { v: 1, tenant: 'mock-user', agent: id, ts: last.ts, seq: 0, prev_checkpoint: '0'.repeat(64), heads, heads_root: 'a'.repeat(64), events: events.length },
      signature: 'bW9jay1zaWduYXR1cmU=',
      key_id: 'mock0000key00001',
      hash: 'b'.repeat(64),
    },
  ];
}
